packaging_format = 2

id = "petitesannonces"
name = "Petites Annonces"
description.en = "Make your own classified advertising website easily"
description.fr = "Créer simplement et rapidement votre site de Petites Annonces"

version = "0.1.0~ynh4"

maintainers = ["Antoine"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://framagit.org/toitoinebzh/petitesannonces"
code = "https://framagit.org/toitoinebzh/petitesannonces"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/annonces"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.categories]
    ask.fr = "Éditer un fichier categories.csv pour personnaliser les catégories d'annonces ?"
    help.fr  = "Pour éditer le fichier categories.cvs, téléchargez le fichier original en cliquant ici https://framagit.org/anto1ne/petitesannonces/-/raw/master/bdd/categories.csv?ref_type=heads&inline=false, éditez-le localement avec votre éditeur de texte en respectant son format (bien garder les `1;` , `2;`, etc...), puis ajoutez-le en cliquant sur le champ ci-dessus"
    type = "file"
    accept = [".csv"]
    bind = "/tmp/categories.csv"
    redact = true
    optional = true

    [install.regions]
    ask.fr = "Éditer un fichier regions.csv pour personnaliser les lieux des annonces ?"
    help.fr = "Pour éditer le fichier regions.cvs, téléchargez le ici https://framagit.org/anto1ne/petitesannonces/-/raw/master/bdd/regions.csv?ref_type=heads&inline=false, éditez-le  localement avec votre éditeur de texte en respectant son format (bien garder les `1;`, `2;`, etc...), puis ajoutez-le en cliquant sur le champ ci-dessus"
    type = "file"
    accept = [".csv"]
    bind = "/tmp/regions.csv"
    redact = true
    optional = true

[resources]
        [resources.sources.main]
        url = "https://framagit.org/anto1ne/petitesannonces/-/archive/v0.1.0/petitesannonces-v0.1.0.tar.gz"
        sha256 = "78abc1bf7575b394854b3a9bd14a1a29b6ddc2ce64e33f39a7503f63faecf714"
        autoupdate.strategy = "latest_gitlab_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php7.4-fpm, php7.4-mysql"

    [resources.database]
    type = "mysql"
