#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated php-fpm config
ynh_add_fpm_config

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# ADD  CONFIGURATIONS
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template="config.php" --destination="$install_dir/conf/config.php"

chmod 400 "$install_dir/conf/config.php"
chown $app:$app "$install_dir/conf/config.php"

if [ -n "${categories:-}" ]; then
cp $categories "$install_dir/bdd/categories.csv"
chmod o-rwx "$install_dir/bdd/categories.csv"
chown $app:www-data "$install_dir/bdd/categories.csv"
fi

if [ -n "${regions:-}" ]; then
cp $regions "$install_dir/bdd/regions.csv"
chmod o-rwx "$install_dir/bdd/regions.csv"
chown $app:www-data "$install_dir/bdd/regions.csv"
fi

ynh_replace_string --match_string="Mot de passe" --replace_string="Mot de passe (à conserver pour suprimer la supression)" --target_file="$install_dir/vue/vue_ajout.php"

ynh_replace_string --match_string="Petites Annonces" --replace_string="$titre_page" --taget_file="$install_dir/vue/vue_list.php"

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression --message="Configuring SSOwat..." --weight=1

# Installation with curl
ynh_script_progression --message="Finalizing installation..." --weight=1

ynh_local_curl "/install.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
