#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the dedicated nginx config
ynh_config_remove_nginx

# Remove the dedicated php-fpm config
ynh_config_remove_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
